version: "3.8"
services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  init-db:
    build: .
    command: ./scripts/bash/wait-for-it.sh db:5432 -- python -m scripts.create_db
    depends_on:
      - db

  app:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - init-db  # Make sure that db is created before running the app.
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres-data: